-- Fix All Remaining Security Issues from info.txt
-- This script adds basic RLS policies to all remaining tables that have RLS enabled but no policies

-- Function to safely create RLS policies
CREATE OR REPLACE FUNCTION create_rls_policy_if_not_exists(
    table_name text,
    policy_name text,
    policy_definition text
) RETURNS void AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = table_name 
        AND policyname = policy_name
    ) THEN
        EXECUTE policy_definition;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Add basic select policies for all remaining tables
-- These policies allow authenticated users to read data they have access to

-- Activity and analytics tables
SELECT create_rls_policy_if_not_exists('activity_log', 'activity_log_select_policy', 'CREATE POLICY activity_log_select_policy ON activity_log FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('album_analytics', 'album_analytics_select_policy', 'CREATE POLICY album_analytics_select_policy ON album_analytics FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('album_shares', 'album_shares_select_policy', 'CREATE POLICY album_shares_select_policy ON album_shares FOR SELECT USING (auth.uid() = user_id OR shared_with_user_id = auth.uid())');

-- Book club tables
SELECT create_rls_policy_if_not_exists('book_club_books', 'book_club_books_select_policy', 'CREATE POLICY book_club_books_select_policy ON book_club_books FOR SELECT USING (EXISTS (SELECT 1 FROM book_club_members WHERE book_club_id = book_club_books.book_club_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('book_club_discussion_comments', 'book_club_discussion_comments_select_policy', 'CREATE POLICY book_club_discussion_comments_select_policy ON book_club_discussion_comments FOR SELECT USING (EXISTS (SELECT 1 FROM book_club_members WHERE book_club_id = (SELECT book_club_id FROM book_club_discussions WHERE id = book_club_discussion_comments.discussion_id) AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('book_club_discussions', 'book_club_discussions_select_policy', 'CREATE POLICY book_club_discussions_select_policy ON book_club_discussions FOR SELECT USING (EXISTS (SELECT 1 FROM book_club_members WHERE book_club_id = book_club_discussions.book_club_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('book_club_members', 'book_club_members_select_policy', 'CREATE POLICY book_club_members_select_policy ON book_club_members FOR SELECT USING (EXISTS (SELECT 1 FROM book_club_members WHERE group_id = book_club_members.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('book_clubs', 'book_clubs_select_policy', 'CREATE POLICY book_clubs_select_policy ON book_clubs FOR SELECT USING (is_public = true OR EXISTS (SELECT 1 FROM book_club_members WHERE book_club_id = book_clubs.id AND user_id = auth.uid()))');

-- Book-related tables
SELECT create_rls_policy_if_not_exists('book_recommendations', 'book_recommendations_select_policy', 'CREATE POLICY book_recommendations_select_policy ON book_recommendations FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('book_similarity_scores', 'book_similarity_scores_select_policy', 'CREATE POLICY book_similarity_scores_select_policy ON book_similarity_scores FOR SELECT USING (auth.role() = ''authenticated'')');

-- Event-related tables
SELECT create_rls_policy_if_not_exists('event_analytics', 'event_analytics_select_policy', 'CREATE POLICY event_analytics_select_policy ON event_analytics FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_approvals', 'event_approvals_select_policy', 'CREATE POLICY event_approvals_select_policy ON event_approvals FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_books', 'event_books_select_policy', 'CREATE POLICY event_books_select_policy ON event_books FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_books.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_calendar_exports', 'event_calendar_exports_select_policy', 'CREATE POLICY event_calendar_exports_select_policy ON event_calendar_exports FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_categories', 'event_categories_select_policy', 'CREATE POLICY event_categories_select_policy ON event_categories FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('event_chat_messages', 'event_chat_messages_select_policy', 'CREATE POLICY event_chat_messages_select_policy ON event_chat_messages FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_chat_messages.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_chat_rooms', 'event_chat_rooms_select_policy', 'CREATE POLICY event_chat_rooms_select_policy ON event_chat_rooms FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_chat_rooms.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_creator_permissions', 'event_creator_permissions_select_policy', 'CREATE POLICY event_creator_permissions_select_policy ON event_creator_permissions FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_financials', 'event_financials_select_policy', 'CREATE POLICY event_financials_select_policy ON event_financials FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_interests', 'event_interests_select_policy', 'CREATE POLICY event_interests_select_policy ON event_interests FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_livestreams', 'event_livestreams_select_policy', 'CREATE POLICY event_livestreams_select_policy ON event_livestreams FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_livestreams.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_locations', 'event_locations_select_policy', 'CREATE POLICY event_locations_select_policy ON event_locations FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_locations.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_media', 'event_media_select_policy', 'CREATE POLICY event_media_select_policy ON event_media FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_media.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_permission_requests', 'event_permission_requests_select_policy', 'CREATE POLICY event_permission_requests_select_policy ON event_permission_requests FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_questions', 'event_questions_select_policy', 'CREATE POLICY event_questions_select_policy ON event_questions FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_questions.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_reminders', 'event_reminders_select_policy', 'CREATE POLICY event_reminders_select_policy ON event_reminders FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_sessions', 'event_sessions_select_policy', 'CREATE POLICY event_sessions_select_policy ON event_sessions FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_sessions.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_shares', 'event_shares_select_policy', 'CREATE POLICY event_shares_select_policy ON event_shares FOR SELECT USING (auth.uid() = user_id OR shared_with_user_id = auth.uid())');
SELECT create_rls_policy_if_not_exists('event_speakers', 'event_speakers_select_policy', 'CREATE POLICY event_speakers_select_policy ON event_speakers FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_speakers.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_sponsors', 'event_sponsors_select_policy', 'CREATE POLICY event_sponsors_select_policy ON event_sponsors FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_sponsors.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_staff', 'event_staff_select_policy', 'CREATE POLICY event_staff_select_policy ON event_staff FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_staff.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_surveys', 'event_surveys_select_policy', 'CREATE POLICY event_surveys_select_policy ON event_surveys FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_surveys.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_tags', 'event_tags_select_policy', 'CREATE POLICY event_tags_select_policy ON event_tags FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = event_tags.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('event_types', 'event_types_select_policy', 'CREATE POLICY event_types_select_policy ON event_types FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('event_views', 'event_views_select_policy', 'CREATE POLICY event_views_select_policy ON event_views FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('event_waitlists', 'event_waitlists_select_policy', 'CREATE POLICY event_waitlists_select_policy ON event_waitlists FOR SELECT USING (auth.uid() = user_id)');

-- Feed and social tables
SELECT create_rls_policy_if_not_exists('feed_entry_tags', 'feed_entry_tags_select_policy', 'CREATE POLICY feed_entry_tags_select_policy ON feed_entry_tags FOR SELECT USING (EXISTS (SELECT 1 FROM feed_entries WHERE id = feed_entry_tags.feed_entry_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('follow_target_types', 'follow_target_types_select_policy', 'CREATE POLICY follow_target_types_select_policy ON follow_target_types FOR SELECT USING (auth.role() = ''authenticated'')');

-- Group-related tables (simplified policies)
SELECT create_rls_policy_if_not_exists('group_achievements', 'group_achievements_select_policy', 'CREATE POLICY group_achievements_select_policy ON group_achievements FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_achievements.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_analytics', 'group_analytics_select_policy', 'CREATE POLICY group_analytics_select_policy ON group_analytics FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_analytics.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_announcements', 'group_announcements_select_policy', 'CREATE POLICY group_announcements_select_policy ON group_announcements FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_announcements.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_audit_log', 'group_audit_log_select_policy', 'CREATE POLICY group_audit_log_select_policy ON group_audit_log FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_audit_log.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_author_events', 'group_author_events_select_policy', 'CREATE POLICY group_author_events_select_policy ON group_author_events FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_author_events.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_book_list_items', 'group_book_list_items_select_policy', 'CREATE POLICY group_book_list_items_select_policy ON group_book_list_items FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = (SELECT group_id FROM group_book_lists WHERE id = group_book_list_items.list_id) AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_book_lists', 'group_book_lists_select_policy', 'CREATE POLICY group_book_lists_select_policy ON group_book_lists FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_book_lists.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_book_reviews', 'group_book_reviews_select_policy', 'CREATE POLICY group_book_reviews_select_policy ON group_book_reviews FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_book_reviews.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_book_swaps', 'group_book_swaps_select_policy', 'CREATE POLICY group_book_swaps_select_policy ON group_book_swaps FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_book_swaps.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_book_wishlist_items', 'group_book_wishlist_items_select_policy', 'CREATE POLICY group_book_wishlist_items_select_policy ON group_book_wishlist_items FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = (SELECT group_id FROM group_book_wishlists WHERE id = group_book_wishlist_items.wishlist_id) AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_book_wishlists', 'group_book_wishlists_select_policy', 'CREATE POLICY group_book_wishlists_select_policy ON group_book_wishlists FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_book_wishlists.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_bots', 'group_bots_select_policy', 'CREATE POLICY group_bots_select_policy ON group_bots FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_bots.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_chat_channels', 'group_chat_channels_select_policy', 'CREATE POLICY group_chat_channels_select_policy ON group_chat_channels FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_chat_channels.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_chat_message_attachments', 'group_chat_message_attachments_select_policy', 'CREATE POLICY group_chat_message_attachments_select_policy ON group_chat_message_attachments FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = (SELECT group_id FROM group_chat_channels WHERE id = (SELECT channel_id FROM group_chat_messages WHERE id = group_chat_message_attachments.message_id)) AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_chat_message_reactions', 'group_chat_message_reactions_select_policy', 'CREATE POLICY group_chat_message_reactions_select_policy ON group_chat_message_reactions FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = (SELECT group_id FROM group_chat_channels WHERE id = (SELECT channel_id FROM group_chat_messages WHERE id = group_chat_message_reactions.message_id)) AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_chat_messages', 'group_chat_messages_select_policy', 'CREATE POLICY group_chat_messages_select_policy ON group_chat_messages FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = (SELECT group_id FROM group_chat_channels WHERE id = group_chat_messages.channel_id) AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_content_moderation_logs', 'group_content_moderation_logs_select_policy', 'CREATE POLICY group_content_moderation_logs_select_policy ON group_content_moderation_logs FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_content_moderation_logs.group_id AND user_id = auth.uid() AND role IN (''admin'', ''moderator'')))');
SELECT create_rls_policy_if_not_exists('group_custom_fields', 'group_custom_fields_select_policy', 'CREATE POLICY group_custom_fields_select_policy ON group_custom_fields FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_custom_fields.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_discussion_categories', 'group_discussion_categories_select_policy', 'CREATE POLICY group_discussion_categories_select_policy ON group_discussion_categories FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_discussion_categories.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_event_feedback', 'group_event_feedback_select_policy', 'CREATE POLICY group_event_feedback_select_policy ON group_event_feedback FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_event_feedback.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_events', 'group_events_select_policy', 'CREATE POLICY group_events_select_policy ON group_events FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_events.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_integrations', 'group_integrations_select_policy', 'CREATE POLICY group_integrations_select_policy ON group_integrations FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_integrations.group_id AND user_id = auth.uid() AND role IN (''admin'', ''moderator'')))');
SELECT create_rls_policy_if_not_exists('group_invites', 'group_invites_select_policy', 'CREATE POLICY group_invites_select_policy ON group_invites FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_invites.group_id AND user_id = auth.uid() AND role IN (''admin'', ''moderator'')))');
SELECT create_rls_policy_if_not_exists('group_leaderboards', 'group_leaderboards_select_policy', 'CREATE POLICY group_leaderboards_select_policy ON group_leaderboards FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_leaderboards.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_member_achievements', 'group_member_achievements_select_policy', 'CREATE POLICY group_member_achievements_select_policy ON group_member_achievements FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_member_achievements.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_member_devices', 'group_member_devices_select_policy', 'CREATE POLICY group_member_devices_select_policy ON group_member_devices FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('group_member_streaks', 'group_member_streaks_select_policy', 'CREATE POLICY group_member_streaks_select_policy ON group_member_streaks FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_member_streaks.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_membership_questions', 'group_membership_questions_select_policy', 'CREATE POLICY group_membership_questions_select_policy ON group_membership_questions FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_membership_questions.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_moderation_logs', 'group_moderation_logs_select_policy', 'CREATE POLICY group_moderation_logs_select_policy ON group_moderation_logs FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_moderation_logs.group_id AND user_id = auth.uid() AND role IN (''admin'', ''moderator'')))');
SELECT create_rls_policy_if_not_exists('group_onboarding_checklists', 'group_onboarding_checklists_select_policy', 'CREATE POLICY group_onboarding_checklists_select_policy ON group_onboarding_checklists FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_onboarding_checklists.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_onboarding_progress', 'group_onboarding_progress_select_policy', 'CREATE POLICY group_onboarding_progress_select_policy ON group_onboarding_progress FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_onboarding_progress.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_onboarding_tasks', 'group_onboarding_tasks_select_policy', 'CREATE POLICY group_onboarding_tasks_select_policy ON group_onboarding_tasks FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_onboarding_tasks.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_poll_votes', 'group_poll_votes_select_policy', 'CREATE POLICY group_poll_votes_select_policy ON group_poll_votes FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = (SELECT group_id FROM group_polls WHERE id = group_poll_votes.poll_id) AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_polls', 'group_polls_select_policy', 'CREATE POLICY group_polls_select_policy ON group_polls FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_polls.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_reading_challenge_progress', 'group_reading_challenge_progress_select_policy', 'CREATE POLICY group_reading_challenge_progress_select_policy ON group_reading_challenge_progress FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_reading_challenge_progress.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_reading_challenges', 'group_reading_challenges_select_policy', 'CREATE POLICY group_reading_challenges_select_policy ON group_reading_challenges FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_reading_challenges.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_reading_progress', 'group_reading_progress_select_policy', 'CREATE POLICY group_reading_progress_select_policy ON group_reading_progress FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_reading_progress.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_reading_sessions', 'group_reading_sessions_select_policy', 'CREATE POLICY group_reading_sessions_select_policy ON group_reading_sessions FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_reading_sessions.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_reports', 'group_reports_select_policy', 'CREATE POLICY group_reports_select_policy ON group_reports FOR SELECT USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM group_members WHERE group_id = group_reports.group_id AND user_id = auth.uid() AND role IN (''admin'', ''moderator'')))');
SELECT create_rls_policy_if_not_exists('group_roles', 'group_roles_select_policy', 'CREATE POLICY group_roles_select_policy ON group_roles FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_roles.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_rules', 'group_rules_select_policy', 'CREATE POLICY group_rules_select_policy ON group_rules FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_rules.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_shared_documents', 'group_shared_documents_select_policy', 'CREATE POLICY group_shared_documents_select_policy ON group_shared_documents FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_shared_documents.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_tags', 'group_tags_select_policy', 'CREATE POLICY group_tags_select_policy ON group_tags FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_tags.group_id AND user_id = auth.uid()))');
SELECT create_rls_policy_if_not_exists('group_types', 'group_types_select_policy', 'CREATE POLICY group_types_select_policy ON group_types FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('group_webhook_logs', 'group_webhook_logs_select_policy', 'CREATE POLICY group_webhook_logs_select_policy ON group_webhook_logs FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_webhook_logs.group_id AND user_id = auth.uid() AND role IN (''admin'', ''moderator'')))');
SELECT create_rls_policy_if_not_exists('group_webhooks', 'group_webhooks_select_policy', 'CREATE POLICY group_webhooks_select_policy ON group_webhooks FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_webhooks.group_id AND user_id = auth.uid() AND role IN (''admin'', ''moderator'')))');
SELECT create_rls_policy_if_not_exists('group_welcome_messages', 'group_welcome_messages_select_policy', 'CREATE POLICY group_welcome_messages_select_policy ON group_welcome_messages FOR SELECT USING (EXISTS (SELECT 1 FROM group_members WHERE group_id = group_welcome_messages.group_id AND user_id = auth.uid()))');

-- Reference and lookup tables
SELECT create_rls_policy_if_not_exists('id_mappings', 'id_mappings_select_policy', 'CREATE POLICY id_mappings_select_policy ON id_mappings FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('image_tag_mappings', 'image_tag_mappings_select_policy', 'CREATE POLICY image_tag_mappings_select_policy ON image_tag_mappings FOR SELECT USING (EXISTS (SELECT 1 FROM images WHERE id = image_tag_mappings.image_id AND (user_id = auth.uid() OR is_public = true)))');
SELECT create_rls_policy_if_not_exists('image_tags', 'image_tags_select_policy', 'CREATE POLICY image_tags_select_policy ON image_tags FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('image_types', 'image_types_select_policy', 'CREATE POLICY image_types_select_policy ON image_types FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('invoices', 'invoices_select_policy', 'CREATE POLICY invoices_select_policy ON invoices FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('list_followers', 'list_followers_select_policy', 'CREATE POLICY list_followers_select_policy ON list_followers FOR SELECT USING (auth.uid() = user_id OR followed_user_id = auth.uid())');
SELECT create_rls_policy_if_not_exists('media_attachments', 'media_attachments_select_policy', 'CREATE POLICY media_attachments_select_policy ON media_attachments FOR SELECT USING (auth.uid() = user_id OR is_public = true)');
SELECT create_rls_policy_if_not_exists('mentions', 'mentions_select_policy', 'CREATE POLICY mentions_select_policy ON mentions FOR SELECT USING (auth.uid() = mentioned_user_id OR auth.uid() = mentioned_by_user_id)');
SELECT create_rls_policy_if_not_exists('payment_methods', 'payment_methods_select_policy', 'CREATE POLICY payment_methods_select_policy ON payment_methods FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('payment_transactions', 'payment_transactions_select_policy', 'CREATE POLICY payment_transactions_select_policy ON payment_transactions FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('personalized_recommendations', 'personalized_recommendations_select_policy', 'CREATE POLICY personalized_recommendations_select_policy ON personalized_recommendations FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('prices', 'prices_select_policy', 'CREATE POLICY prices_select_policy ON prices FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('promo_codes', 'promo_codes_select_policy', 'CREATE POLICY promo_codes_select_policy ON promo_codes FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('reactions', 'reactions_select_policy', 'CREATE POLICY reactions_select_policy ON reactions FOR SELECT USING (EXISTS (SELECT 1 FROM posts WHERE id = reactions.post_id AND (is_public = true OR user_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('reading_list_items', 'reading_list_items_select_policy', 'CREATE POLICY reading_list_items_select_policy ON reading_list_items FOR SELECT USING (EXISTS (SELECT 1 FROM reading_lists WHERE id = reading_list_items.list_id AND (is_public = true OR user_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('reading_series', 'reading_series_select_policy', 'CREATE POLICY reading_series_select_policy ON reading_series FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('reading_stats_daily', 'reading_stats_daily_select_policy', 'CREATE POLICY reading_stats_daily_select_policy ON reading_stats_daily FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('reading_streaks', 'reading_streaks_select_policy', 'CREATE POLICY reading_streaks_select_policy ON reading_streaks FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('review_likes', 'review_likes_select_policy', 'CREATE POLICY review_likes_select_policy ON review_likes FOR SELECT USING (EXISTS (SELECT 1 FROM book_reviews WHERE id = review_likes.review_id AND (is_public = true OR user_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('reviews', 'reviews_select_policy', 'CREATE POLICY reviews_select_policy ON reviews FOR SELECT USING (is_public = true OR auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('series_events', 'series_events_select_policy', 'CREATE POLICY series_events_select_policy ON series_events FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('session_registrations', 'session_registrations_select_policy', 'CREATE POLICY session_registrations_select_policy ON session_registrations FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('similar_books', 'similar_books_select_policy', 'CREATE POLICY similar_books_select_policy ON similar_books FOR SELECT USING (auth.role() = ''authenticated'')');
SELECT create_rls_policy_if_not_exists('statuses', 'statuses_select_policy', 'CREATE POLICY statuses_select_policy ON statuses FOR SELECT USING (auth.uid() = user_id OR is_public = true)');
SELECT create_rls_policy_if_not_exists('survey_questions', 'survey_questions_select_policy', 'CREATE POLICY survey_questions_select_policy ON survey_questions FOR SELECT USING (EXISTS (SELECT 1 FROM event_surveys WHERE id = survey_questions.survey_id AND EXISTS (SELECT 1 FROM events WHERE id = event_surveys.event_id AND (is_public = true OR creator_id = auth.uid()))))');
SELECT create_rls_policy_if_not_exists('survey_responses', 'survey_responses_select_policy', 'CREATE POLICY survey_responses_select_policy ON survey_responses FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('sync_state', 'sync_state_select_policy', 'CREATE POLICY sync_state_select_policy ON sync_state FOR SELECT USING (auth.uid() = user_id)');
SELECT create_rls_policy_if_not_exists('ticket_benefits', 'ticket_benefits_select_policy', 'CREATE POLICY ticket_benefits_select_policy ON ticket_benefits FOR SELECT USING (EXISTS (SELECT 1 FROM ticket_types WHERE id = ticket_benefits.ticket_type_id AND EXISTS (SELECT 1 FROM events WHERE id = ticket_types.event_id AND (is_public = true OR creator_id = auth.uid()))))');
SELECT create_rls_policy_if_not_exists('ticket_types', 'ticket_types_select_policy', 'CREATE POLICY ticket_types_select_policy ON ticket_types FOR SELECT USING (EXISTS (SELECT 1 FROM events WHERE id = ticket_types.event_id AND (is_public = true OR creator_id = auth.uid())))');
SELECT create_rls_policy_if_not_exists('tickets', 'tickets_select_policy', 'CREATE POLICY tickets_select_policy ON tickets FOR SELECT USING (auth.uid() = user_id)');

-- Clean up the helper function
DROP FUNCTION IF EXISTS create_rls_policy_if_not_exists(text, text, text);

-- Summary
SELECT 'All remaining security issues fixed: Basic RLS policies added to all tables mentioned in info.txt' as status; 