-- Seed Posts Table with Sample Data
-- This script populates the posts table with realistic sample data
-- that matches the current enterprise-grade schema

-- First, ensure we have some users to work with
-- Note: These should match actual users in your auth.users table
-- You may need to adjust these UUIDs to match your actual users

-- Insert sample posts for testing
INSERT INTO public.posts (
    id,
    user_id,
    content,
    image_url,
    link_url,
    created_at,
    updated_at,
    visibility,
    allowed_user_ids,
    is_hidden,
    is_deleted,
    entity_type,
    entity_id,
    content_type,
    metadata,
    content_summary,
    media_files,
    scheduled_at,
    published_at,
    tags,
    categories,
    languages,
    regions,
    content_warnings,
    sensitive_content,
    age_restriction,
    seo_title,
    seo_description,
    seo_keywords,
    publish_status,
    view_count,
    like_count,
    comment_count,
    share_count,
    bookmark_count,
    engagement_score,
    trending_score,
    is_featured,
    is_pinned,
    is_verified,
    last_activity_at,
    enterprise_features
) VALUES 
  (
    'e1fcb778-38f7-4989-a12e-6e39e85274c6', -- This is the exact ID the frontend is trying to edit
    '2474659f-003e-4faa-8c53-9969c33f20b2', -- This should match your current user ID
    '{"text": "Just finished reading \"The Great Gatsby\" by F. Scott Fitzgerald. What a beautifully written novel about the American Dream and its illusions. The prose is absolutely stunning! 📚✨", "type": "text", "summary": "Book review of The Great Gatsby", "hashtags": ["books", "reading", "classics"], "mentions": []}',
    NULL,
    NULL,
    now() - interval '1 day',
    now() - interval '1 day',
    'public',
    NULL,
    false,
    false,
    'user',
    '2474659f-003e-4faa-8c53-9969c33f20b2',
    'text',
    '{"source": "manual", "content_rating": "G", "language": "en"}',
    'Book review of The Great Gatsby',
    '[]',
    NULL,
    now() - interval '1 day',
    ARRAY['books', 'reading', 'classics'],
    ARRAY['literature', 'fiction'],
    ARRAY['en'],
    ARRAY['US'],
    ARRAY[],
    false,
    NULL,
    'Book Review: The Great Gatsby',
    'A beautiful review of F. Scott Fitzgerald\'s classic novel',
    ARRAY['books', 'reading', 'classics', 'literature'],
    'published',
    15,
    8,
    3,
    2,
    1,
    0.75,
    0.6,
    false,
    false,
    false,
    now() - interval '1 day',
    '{"created_at": "' || (now() - interval '1 day')::text || '", "content_moderation": {"status": "approved", "score": 0.95}}'
  ),
  (
    gen_random_uuid(),
    '2474659f-003e-4faa-8c53-9969c33f20b2',
    '{"text": "Started my 2025 reading challenge! Goal: 50 books this year. Currently reading \"1984\" by George Orwell. Anyone else tackling this classic? 🤔📖", "type": "text", "summary": "Reading challenge update", "hashtags": ["reading", "challenge", "1984"], "mentions": []}',
    NULL,
    NULL,
    now() - interval '3 days',
    now() - interval '3 days',
    'public',
    NULL,
    false,
    false,
    'user',
    '2474659f-003e-4faa-8c53-9969c33f20b2',
    'text',
    '{"source": "manual", "content_rating": "G", "language": "en"}',
    'Reading challenge update',
    '[]',
    NULL,
    now() - interval '3 days',
    ARRAY['reading', 'challenge', '1984'],
    ARRAY['goals', 'reading'],
    ARRAY['en'],
    ARRAY['US'],
    ARRAY[],
    false,
    NULL,
    '2025 Reading Challenge Update',
    'Update on my 2025 reading goal of 50 books',
    ARRAY['reading', 'challenge', 'goals', 'books'],
    'published',
    23,
    12,
    5,
    1,
    2,
    0.82,
    0.7,
    false,
    false,
    false,
    now() - interval '3 days',
    '{"created_at": "' || (now() - interval '3 days')::text || '", "content_moderation": {"status": "approved", "score": 0.98}}'
  ),
  (
    gen_random_uuid(),
    '2474659f-003e-4faa-8c53-9969c33f20b2',
    '{"text": "New book added to my collection: \"Pride and Prejudice\" by Jane Austen. Can\'t wait to dive into this classic romance! 💕📚", "type": "text", "summary": "New book addition", "hashtags": ["books", "classics", "romance"], "mentions": []}',
    NULL,
    NULL,
    now() - interval '1 week',
    now() - interval '1 week',
    'public',
    NULL,
    false,
    false,
    'user',
    '2474659f-003e-4faa-8c53-9969c33f20b2',
    'text',
    '{"source": "manual", "content_rating": "G", "language": "en"}',
    'New book addition',
    '[]',
    NULL,
    now() - interval '1 week',
    ARRAY['books', 'classics', 'romance'],
    ARRAY['literature', 'fiction'],
    ARRAY['en'],
    ARRAY['US'],
    ARRAY[],
    false,
    NULL,
    'New Book: Pride and Prejudice',
    'Added Jane Austen\'s classic to my collection',
    ARRAY['books', 'classics', 'romance', 'literature'],
    'published',
    8,
    4,
    1,
    0,
    0,
    0.65,
    0.4,
    false,
    false,
    false,
    now() - interval '1 week',
    '{"created_at": "' || (now() - interval '1 week')::text || '", "content_moderation": {"status": "approved", "score": 0.97}}'
  );

-- Verify the data was inserted
SELECT 
    id,
    user_id,
    content->>'text' as content_text,
    content_type,
    publish_status,
    created_at,
    view_count,
    like_count,
    comment_count
FROM public.posts 
ORDER BY created_at DESC;
